import type { SharedPost } from "@/lib/forumStore";

export const forumSeedPosts: SharedPost[] = [
  {
    id: "1",
    author: "Anna M.",
    title: "Frage zur linearen Algebra Aufgabe 3",
    content: "Kann mir jemand bei der Eigenwertberechnung helfen? Ich komme bei der 3x3 Matrix nicht weiter.",
    date: "vor 2 Stunden",
    likes: 5,
    replies: 3,
    tag: "frage",
    standort: "DHBW Stuttgart",
    studiengang: "Wirtschaftsinformatik",
    kurs: "WWI23A",
  },
  {
    id: "2",
    author: "Tim K.",
    title: "Lerngruppe für Statistik Klausur",
    content: "Wer hat Lust auf eine kursübergreifende Lerngruppe für die Statistik-Klausur? Online via Discord.",
    date: "vor 5 Stunden",
    likes: 12,
    replies: 8,
    tag: "lerngruppe",
    standort: "DHBW Mannheim",
    studiengang: "BWL-Industrie",
    kurs: "WIN22",
  },
  {
    id: "3",
    author: "Lena S.",
    title: "Zusammenfassung Vorlesung 7 - Algorithmen",
    content: "Habe meine Zusammenfassung zur Sortieralgorithmen-Vorlesung hochgeladen. Schaut gerne rein!",
    date: "gestern",
    likes: 20,
    replies: 4,
    tag: "material",
    standort: "DHBW Karlsruhe",
    studiengang: "Informatik",
    kurs: "TINF22",
  },
];
