export const STUDIENFAECHER = [
  "Angewandte Informatik",
  "Artificial Intelligence",
  "Bauingenieurwesen",
  "Betriebswirtschaftslehre - Bank",
  "Betriebswirtschaftslehre - Dienstleistungen",
  "Betriebswirtschaftslehre - Facility Management",
  "Betriebswirtschaftslehre - Handel",
  "Betriebswirtschaftslehre - Industrie",
  "Betriebswirtschaftslehre - International Business",
  "Betriebswirtschaftslehre - Messe/Kongress/Event",
  "Betriebswirtschaftslehre - Spedition/Logistik",
  "BWL - Digital Business Management",
  "BWL - Gesundheitsmanagement",
  "BWL - Steuer- und Prüfungswesen",
  "BWL - Wirtschaftsprüfung",
  "Data Science",
  "Digitales Produktmanagement",
  "E-Commerce",
  "Elektrotechnik",
  "Energiewirtschaft",
  "Fahrzeugtechnik",
  "Informationsmanagement",
  "Informationssicherheit",
  "Informatik",
  "Internationale Betriebswirtschaftslehre",
  "IT Security",
  "Künstliche Intelligenz",
  "Maschinenbau",
  "Mechatronik",
  "Medieninformatik",
  "Medientechnik",
  "Medizinische Informatik",
  "Online-Medien",
  "Software Engineering",
  "Technische Informatik",
  "Verfahrenstechnik",
  "Wirtschaftsinformatik",
  "Wirtschaftsingenieurwesen",
  "Wirtschaftsrecht",
] as const;

export type Studienfach = (typeof STUDIENFAECHER)[number];
